"""empty message

Revision ID: 19b3c8de3e78
Revises: 
Create Date: 2024-11-05 00:16:21.915749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b3c8de3e78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        #batch_op.drop_constraint('messages_room_id_fkey', type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###
