"""Add nickname field to User model

Revision ID: 68212d64661c
Revises: 8c6f059e4161
Create Date: 2024-10-22 22:05:53.498426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68212d64661c'
down_revision = '8c6f059e4161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
